version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: waze
      MONGO_INITDB_ROOT_PASSWORD: miata123
      MONGO_INITDB_DATABASE: waze

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  
  sgt:
    build: .
    environment:
      - KAFKA_SERVER=kafka
      - KAFKA_PORT=9092
      - MONGO_URI=mongodb://waze:miata123@mongo:27017/?maxPoolSize=20&w=majority
    depends_on:
      - kafka
      - mongo
    entrypoint: >
      /bin/sh -c "sleep 10 && ./sgt randomSentence"